services:
  localstack:
    image: "localstack/localstack"
    container_name: localstack_demo
    environment:
      - SERVICES=s3,sqs
      - EAGER_SERVICE_LOADING=1
      - DATA_DIR=/tmp/localstack
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
